# Generated by Django 3.1.2 on 2021-03-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=30)),
                ('p_country', models.CharField(max_length=30)),
                ('p_image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='tt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField(max_length=4)),
                ('match', models.IntegerField(max_length=4)),
                ('hundreds', models.IntegerField(max_length=4)),
                ('avg', models.FloatField(max_length=8)),
                ('strikrate', models.FloatField(max_length=8)),
                ('wickets', models.IntegerField(max_length=4)),
                ('economy', models.FloatField(max_length=8)),
            ],
        ),
    ]
