# Generated by Django 3.1.2 on 2021-03-26 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crick', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tt',
            name='players_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crick.players'),
        ),
    ]
