# Generated by Django 3.1.2 on 2021-03-26 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crick', '0002_tt_players_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tt',
            old_name='players_id',
            new_name='player',
        ),
    ]
