# Generated by Django 3.1.2 on 2021-04-04 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crick', '0003_auto_20210326_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tt',
            old_name='match',
            new_name='matches',
        ),
        migrations.RenameField(
            model_name='tt',
            old_name='player',
            new_name='player_id',
        ),
    ]
