# Generated by Django 3.1.2 on 2021-04-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crick', '0004_auto_20210404_0723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tt',
            old_name='player_id',
            new_name='player',
        ),
    ]
