# Generated by Django 3.1.2 on 2021-04-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crick', '0006_auto_20210406_0343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tt',
            old_name='strikrate',
            new_name='strikerate',
        ),
    ]
